phrases = ['all-day schooling',
'ampliación de escuelas de jornada',
'ampliación de la jornada escolar',
'attend school full time',
'complete double schooling',
'complete school day',
'doble escolaridad',
'doble jornada escolar',
'double schooling',
'double shift schooling',
'double shift schools',
'double-shifting in schools',
'escuela tiempo completo',
'extended school day',
'extended school hours',
'extending the school day',
'extension of all-day schools',
'extension of school coverage',
'extension of the school day',
'full engagement in school',
'full school days',
'full time school',
'full time school day',
'full-time education',
'full-time School Day',
'full-time schools',
'JEC',
'jornada escolar completa',
'jornada escolar completa',
'jornada escolar extendida',
'jornada única',
'lengthening the School Day',
'long school day',
'longer School Day',
'school full time',
'school full time',
'school full-time',
'the school day extension'
]

methodology = ['randomized',
'impact evaluations',
'experiments',
'randomized controlled trials',
'evaluación de impacto',
'experimentos aleatorios',
'RCT',
'experimentos sociales controlados',
'experimentos naturales',
'experimentos aleatorios',
'experimentos sociales',
'cuasi experimentos',
'diferencias en diferencias',
'método de emparejamiento',
'variables instrumentales',
'regresión discontinua',
'RD',
'estudio aleatorio',
'evaluaciones de impacto',
'ensayos controlados aleatorios',
'ECA',
'ensayos aleatorios controlados',
'estudios controlados al azar',
'social experiments',
'controlled experiments',
'economic experiments' ,
'randomized experiments',
'quasi-experiments',
'difference in differences',
'propensity-score matching',
'PSM',
'instrumental variables'
]

population = ['school',
'school students',
'estudiantes de colegio',
'básica',
'media',
'secundaria',
'middle school',
'secondary',
'secondary education',
'secondary school',
'high school',
'basic school',
'elementary school',
'primary school'
]

test = ['math', 'reading', 'mathematics', 'language', 'standard deviation', 'academic achievement', 'matematicas',
        'desviacion estandar', 'lenguaje', 'logro academico']