url= 'https://ezproxy.uniandes.edu.co:8443/login?url=https://apps.webofknowledge.com/WOS_GeneralSearch_input.do?product=WOS&search_mode=GeneralSearch'
article_base_url = 'https://www-webofscience-com.ezproxyegre.uniandes.edu.co:8843'
search_term = '"Longer School Day" OR "Full time school day" OR "Complete school day" OR "Long school day" OR "Lengthening the School Day" OR "Double shift schooling" OR "Double shift schools" OR "Double-shifting in schools" OR "Double schooling" OR "Full school days" OR "Extending the school day" OR "Extension of the school day" OR "The school day extension" OR "Full time school" OR "School full time" OR "Extended school day" OR "Extended school hours"'
output = 'WebOfScience.xlsx'
page = 'PageWebofScience.txt'
user = ''
password = ''